# Alertmanager 設定檔
# 用於管理告警通知

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@xsong.us'
  smtp_auth_username: 'alertmanager@xsong.us'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://localhost:5001/'

- name: 'critical-alerts'
  email_configs:
  - to: 'me@xsong.us'
    headers:
      subject: '[CRITICAL] xsong.us 網站告警'
    html: |
      {{ range .Alerts }}
      <h2>告警: {{ .Annotations.summary }}</h2>
      <p>描述: {{ .Annotations.description }}</p>
      <p>時間: {{ .StartsAt }}</p>
      {{ end }}

- name: 'warning-alerts'
  email_configs:
  - to: 'me@xsong.us'
    headers:
      subject: '[WARNING] xsong.us 網站告警'
    html: |
      {{ range .Alerts }}
      <h2>告警: {{ .Annotations.summary }}</h2>
      <p>描述: {{ .Annotations.description }}</p>
      <p>時間: {{ .StartsAt }}</p>
      {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']