# Blackbox Exporter 設定檔
# 用於監控網站可用性和效能

modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 201, 202, 203, 204, 205, 206, 207, 208, 226]
      method: GET
      headers:
        User-Agent: "Blackbox Exporter"
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4" # defaults to "ip6"
      ip_protocol_fallback: true

  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 201, 202, 203, 204, 205, 206, 207, 208, 226]
      method: POST
      headers:
        Content-Type: application/json
        User-Agent: "Blackbox Exporter"
      body: '{"test": "data"}'
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: false

  tcp_connect:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ip4"

  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"

  dns_tcp:
    prober: dns
    timeout: 5s
    dns:
      query_name: "example.com"
      query_type: "A"
      valid_rcodes:
        - NOERROR
      validate_answer_rrs:
        fail_if_matches_regexp:
          - ".*\\.malicious\\..*"
        fail_if_not_matches_regexp:
          - ".*\\.example\\..*"
      validate_authority_rrs:
        fail_if_not_matches_regexp:
          - ".*\\.ns\\.example\\..*"
      validate_additional_rrs:
        fail_if_matches_regexp:
          - ".*\\.malicious\\..*"
